Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QRMenu.Models
{
    public class Cart
    {
        public int CartId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    }
}

Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QRMenu.Models
{
    public class Menu
    {
        public int MenuId { get; set; }
        public string ItemNameAR { get; set; }
        public string ItemNameEN { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        //public string LogoImageURL { get; set; }
        public string Details { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

Areas/Administrator/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QRMenu.Models;
using System.Text.Json;

namespace QRMenu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize(Roles = "DemoAdmin")]
    public class MenusController : Controller
    {
        private readonly AppDBContext _context;

        public MenusController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Administrator/Menus
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Menus.Include(m => m.Category);
            return View(await appDBContext.ToListAsync());
        }

        // GET: Administrator/Menus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Administrator/Menus/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "NameAR");
            var model = new Menu();
            return View(model);
            
        }

   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuId,ItemNameAR,ItemNameEN,Price,ImageUrl,Details,CategoryId")] Menu menu , IFormFile ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null && ImageUrl.Length > 0)
                {
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageUrl.FileName;

                    // Determine the path where you want to save the image
                    var imagePath = Path.Combine("wwwroot/ItemImages", uniqueFileName);

                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await ImageUrl.CopyToAsync(stream);
                    }
                    menu.ImageUrl = "../ItemImages/" + uniqueFileName;
                }
            
                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", menu.CategoryId);
            return View(menu);
        }

        // GET: Administrator/Menus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "NameAR", menu.CategoryId);
            return View(menu);
        }

        // POST: Administrator/Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MenuId,ItemNameAR,ItemNameEN,Price,ImageUrl,Details,CategoryId")] Menu menu , IFormFile ImageUrl)
        {
            if (id != menu.MenuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageUrl != null && ImageUrl.Length > 0)
                    {
                        var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageUrl.FileName;

                        // Determine the path where you want to save the image
                        var imagePath = Path.Combine("wwwroot/ItemImages", uniqueFileName);

                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await ImageUrl.CopyToAsync(stream);
                        }
                        menu.ImageUrl = "../ItemImages/" + uniqueFileName;
                    }
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.MenuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", menu.CategoryId);
            return View(menu);
        }

        // GET: Administrator/Menus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Administrator/Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menu = await _context.Menus.FindAsync(id);
            _context.Menus.Remove(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
            return _context.Menus.Any(e => e.MenuId == id);
        }

        public IActionResult OrderDetails(int orderId)
        {
            // Retrieve the order with the specified orderId from your data source
            Order order = _context.Orders.FirstOrDefault(o => o.OrderId == orderId);

            if (order == null)
            {
                return NotFound();
            }
            var cartItemsJson = JsonSerializer.Serialize(order.CartItemsJson);
            ViewBag.CartItemsJson = cartItemsJson;
            // Pass the order to the OrderDetails view
            return View(order);
        }
        public IActionResult AllOrders()
        {
            // Retrieve a list of all orders from your data source, sorted by CreatedAt
            List<Order> orders = _context.Orders.OrderByDescending(o => o.CreatedAt).ToList();

            // Pass the sorted list of orders to the AllOrders view
            return View(orders);
        }
    }
}

Controllers/MenusController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using QRMenu.Models;
using QRMenu.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.Text.Json;

namespace QRMenu.Controllers
{


    public class MenusController : Controller
    {


        private AppDBContext db;
        public MenusController(AppDBContext _db)
        {
            db = _db;
        }
        Menu M = new Menu();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Demo()
        {
           
            var imageUrl = db.Images
                           .Where(row => row.UserId == "007b4077-4716-4031-8d8e-a24560d38032")
                         .OrderByDescending(row => row.Id)
                           .Select(row => row.LogoUrl)
                           .FirstOrDefault();
            ViewBag.Logo = "../LogoImages/" + imageUrl;
            List<int> uniqueCategoryIds = db.Menus
                .Select(menu => menu.CategoryId)
                .Distinct()
                .ToList();
            ViewBag.CategoryList = uniqueCategoryIds;

            return View(db.Categories);
         

        }
        public IActionResult Demo2()
        {

            var imageUrl = db.Images
                           .Where(row => row.UserId == "007b4077-4716-4031-8d8e-a24560d38032")
                         .OrderByDescending(row => row.Id)
                           .Select(row => row.LogoUrl)
                           .FirstOrDefault();
            ViewBag.Logo = "../LogoImages/" + imageUrl;
            List<int> uniqueCategoryIds = db.Menus
                .Select(menu => menu.CategoryId)
                .Distinct()
                .ToList();
            ViewBag.CategoryList = uniqueCategoryIds;

            return View(db.Categories);


        }
        public IActionResult Shady()
        {

            var imageUrl = db.Images
                           .Where(row => row.UserId == "f22e519a-6ae1-4e31-addc-82a872c54e1c")
                         .OrderByDescending(row => row.Id)
                           .Select(row => row.LogoUrl)
                           .FirstOrDefault();
            ViewBag.Logo = "../LogoImages/" + imageUrl;
            List<int> uniqueCategoryIds = db.shadyMenus
                .Select(menu => menu.CategoryId)
                .Distinct()
                .ToList();
            ViewBag.CategoryList = uniqueCategoryIds;

            return View(db.Categories);

        }

        [HttpPost]
        public IActionResult AddToCart(string itemNameAR, decimal price, int quantity)
        {
            // Retrieve the existing cart items from the session or create a new list
            List<Cart> cartItems;
            string cartItemsJson = HttpContext.Session.GetString("Carts");

            if (cartItemsJson != null)
            {
                cartItems = JsonConvert.DeserializeObject<List<Cart>>(cartItemsJson);
            }
            else
            {
                cartItems = new List<Cart>();
            }

            // Add the item(s) to the cart with the specified quantity
            for (int i = 0; i < quantity; i++)
            {
                cartItems.Add(new Cart { Name = itemNameAR, Price = price });
            }

            // Serialize the list to JSON and save it in the session
            HttpContext.Session.SetString("Carts", JsonConvert.SerializeObject(cartItems));

            // Return a response if necessary (e.g., success message)
            return Json(new { success = true });
        }
        public IActionResult Cart()
        {
            var cartItemsJson = HttpContext.Session.GetString("Carts");

            if (cartItemsJson != null)
            {
                List<Cart> cartItems = JsonConvert.DeserializeObject<List<Cart>>(cartItemsJson);
                return View(cartItems);
            }
            else
            {
                // Handle the case when the cart is empty or hasn't been initialized
                List<Cart> emptyCart = new List<Cart>();
                return View(emptyCart);
            }
        }
        public IActionResult ShadyCart()
        {
            var cartItemsJson = HttpContext.Session.GetString("Carts");

            if (cartItemsJson != null)
            {
                List<Cart> cartItems = JsonConvert.DeserializeObject<List<Cart>>(cartItemsJson);
                return View(cartItems);
            }
            else
            {
                // Handle the case when the cart is empty or hasn't been initialized
                List<Cart> emptyCart = new List<Cart>();
                return View(emptyCart);
            }
        }
        [HttpPost]
        public IActionResult SaveOrder([FromBody] OrderViewModel orderViewModel)
        {
            try
            {
                // Serialize the cartItems list to JSON
                string cartItemsJson = JsonConvert.SerializeObject(orderViewModel.CartItemsJson);

                // Find the Jordan time zone by its id
                TimeZoneInfo jordanTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Jordan Standard Time");

                // Capture the current time in Jordan time zone
                DateTime jordanNow = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, jordanTimeZone);

                // Create a new Order instance and populate its properties
                var order = new Order
                {
                    TableNumber = orderViewModel.TableNumber,
                    CartItemsJson = cartItemsJson, // Store serialized cartItems 
                    CreatedAt = jordanNow  // Capture the current time in Jordan time zone
                };

                // Save the order to the database
                db.Orders.Add(order);
                db.SaveChanges();

                // Return a success response
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                // Handle any errors that occur during the save process
                return Json(new { success = false, error = ex.Message });
            }
        }
    }
}

ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QRMenu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QRMenu.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private AppDBContext db;
        public MenuViewComponent(AppDBContext _db)
        {
            db = _db;
        }

        public IViewComponentResult Invoke(int id, bool someCondition)
        {
            
            IQueryable<Menu> query = db.Menus.OrderByDescending(x => x.MenuId);

            if (someCondition)
            {
                query = query.Where(x => x.CategoryId == id);
            }

            var model =  query.ToList(); // Execute the query

            return View(model);
        }
    }
}

ViewComponents/ShadyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QRMenu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QRMenu.ViewComponents
{
    public class ShadyViewComponent : ViewComponent
    {
        private AppDBContext db;
        public ShadyViewComponent(AppDBContext _db)
        {
            db = _db;
        }

        public IViewComponentResult Invoke(int id, bool someCondition)
        {

            IQueryable<ShadyMenu> query = db.shadyMenus.OrderByDescending(x => x.ShadyMenuId);

            if (someCondition)
            {
                query = query.Where(x => x.CategoryId == id);
            }

            var model = query.ToList(); // Execute the query

            return View(model);
        }
    
}
}

Views/Menus/Demo.cshtml
@model IEnumerable<QRMenu.Models.Category>
@{
    Layout = null;
}

@{

    List<int> myList = ViewBag.CategoryList;

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Menu</title>
    <style>
        /* Stylish restaurant menu design */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .menu {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
            border-radius: 10px;
        }

        h2 {
            text-align: center;
            color: #fd7914;
        }

        .category {
            margin-top: 20px;
            color: #008080;
        }

        .item {
            display: flex;
            align-items: center;
            border: 1px solid #ddd;
            margin-bottom: 10px;
            padding: 15px;
            background-color: #fff;
            border-radius: 10px;
            transition: transform 0.2s ease;
        }

            .item:hover {
                transform: scale(1.02);
            }

            .item img {
                max-width: 100px;
                max-height: 100px;
                border-radius: 10px;
                margin-right: 20px;
                box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
            }

        .item-info {
            flex-grow: 1;
        }

        .item-description {
            color: #555;
            margin-bottom: 5px;
        }

        .item-price {
            font-weight: bold;
            color: #ff6600;
        }

        .quantity {
            display: flex;
            align-items: center;
            margin-top: 5px;
        }

            .quantity input {
                width: 40px;
                padding: 5px;
                border: 1px solid #ddd;
                border-radius: 5px;
                text-align: center;
                font-weight: bold;
            }

        .add-to-cart {
            background-color: #ff6600;
            color: #fff;
            border: none;
            cursor: pointer;
            padding: 8px 15px;
            border-radius: 5px;
            font-weight: bold;
            transition: background-color 0.3s ease;
        }

            .add-to-cart:hover {
                background-color: #e55400;
            }

        .header {
            display: flex;
            align-items: center; /* Center items vertically in the header */
        }

        .logo {
            max-width: 50px; /* Adjust the size of the logo as needed */
            margin-right: 10px; /* Add some spacing between the logo and text */
        }

        h1 {
            color: #fd7914;
            margin: 0; /* Remove default margin to eliminate space around the heading */
        }
        /* Cart icon */
        .cart-icon {
            position: relative;
            float: right; /* Float the icon to the right within the menu div */
            margin-top: -30px; /* Adjust the top margin to position it properly */
            display: flex;
            align-items: center;
            cursor: pointer;
            background-color: white;
            color: #fff;
            border-radius: 50%;
            padding: 8px;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, .2);
        }

            .cart-icon img {
                max-width: 30px; /* Adjust the size of the cart icon image as needed */
                margin-right: 0px; /* Add spacing between the icon and count */
            }

        .cart-count {
            font-weight: bold;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="menu">

        <div class="header">
           
            <img class="logo" src="@ViewBag.Logo" alt="Restaurant Logo">
            <h1 style="font-size : 15pt ">Restaurant Menu</h1>
        </div>
        <div class="cart-icon">
            <a asp-action="Cart" asp-controller="Menus">
            <img src="~/NataHTML/images/cart-icon.png" alt="Shopping Cart">
                </a>
            @*<span class="cart-count">0</span>*@
        </div>
        <!-- Category: Appetizers -->
        @foreach (var item in Model)
        {

            @foreach (var item2 in myList)
            {
                if (item.CategoryId == item2)
                {
                    <div class="category">
                        <label asp-for="@item.CategoryId" name="CategoryId" hidden></label>
                        <h3>     @item.NameAR | @item.NameEN</h3>
                        @await Component.InvokeAsync("Menu", new { id = item.CategoryId, someCondition = true })



                    </div>
                }
            }}
    </div>
</body>
</html>

Views/Menus/Demo2.cshtml
@model IEnumerable<QRMenu.Models.Category>
@{
    Layout = null;
}

@{

    List<int> myList = ViewBag.CategoryList;

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Menu</title>
    <style>
        /* Stylish restaurant menu design */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .menu {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
            border-radius: 10px;
        }

        h2 {
            text-align: center;
            color: #fd7914;
        }

        .category {
            margin-top: 20px;
            color: #008080;
        }

        .item {
            display: flex;
            align-items: center;
            border: 1px solid #ddd;
            margin-bottom: 10px;
            padding: 15px;
            background-color: #fff;
            border-radius: 10px;
            transition: transform 0.2s ease;
        }

            .item:hover {
                transform: scale(1.02);
            }

            .item img {
                max-width: 100px;
                max-height: 100px;
                border-radius: 10px;
                margin-right: 20px;
                box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
            }

        .item-info {
            flex-grow: 1;
        }

        .item-description {
            color: #555;
            margin-bottom: 5px;
        }

        .item-price {
            font-weight: bold;
            color: #ff6600;
        }

        .quantity {
            display: flex;
            align-items: center;
            margin-top: 5px;
        }

            .quantity input {
                width: 40px;
                padding: 5px;
                border: 1px solid #ddd;
                border-radius: 5px;
                text-align: center;
                font-weight: bold;
            }

        .add-to-cart {
            background-color: #ff6600;
            color: #fff;
            border: none;
            cursor: pointer;
            padding: 8px 15px;
            border-radius: 5px;
            font-weight: bold;
            transition: background-color 0.3s ease;
        }

            .add-to-cart:hover {
                background-color: #e55400;
            }

        .header {
            display: flex;
            align-items: center; /* Center items vertically in the header */
        }

        .logo {
            max-width: 50px; /* Adjust the size of the logo as needed */
            margin-right: 10px; /* Add some spacing between the logo and text */
        }

        h1 {
            color: #fd7914;
            margin: 0; /* Remove default margin to eliminate space around the heading */
        }
    </style>
</head>
<body>
    <div class="menu">
        <div class="header">
            <img class="logo" src="@ViewBag.Logo" alt="Restaurant Logo">
            <h1 style="font-size : 15pt ">Restaurant Menu</h1>
        </div>

        <!-- Category: Appetizers -->
        @foreach (var item in Model)
        {

            @foreach (var item2 in myList)
            {
                if (item.CategoryId == item2)
                {
    <div class="category">
        <label asp-for="@item.CategoryId" name="CategoryId" hidden></label>
        <h3>     @item.NameAR | @item.NameEN</h3>
        @await Component.InvokeAsync("Menu", new { id = item.CategoryId, someCondition = true })
        


    </div>
                }
            }}
    </div>
</body>
</html>
 
      
          

     

Views/Menus/Shady.cshtml
@model IEnumerable<QRMenu.Models.Category>
@{
    //ViewData["Title"] = "OurRestaurant";
    Layout = null;

}
@{

    List<int> myList = ViewBag.CategoryList;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon"  href="@ViewBag.Logo">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;800&display=swap" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="~/ShadyMenu/assets/css/style.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <title>The Menu</title>
</head>
<body class="menu-body">

    <div class="menu-header">
        <img src="@ViewBag.Logo" class="menu-logo">
        <h1>Taste It -- Feel It</h1>
    </div>

    <div class="menu-container">
        @foreach (var item in Model)
        {

            @foreach (var item2 in myList)
            {
                if (item.CategoryId == item2)
                {

                    <label asp-for="@item.CategoryId" name="CategoryId" hidden></label>
                    <div class="menu-category">
                        <h1>
                            @item.NameEN | @item.NameAR
                        </h1>
                    </div>

                    <div class="row">


                        @await Component.InvokeAsync("Shady", new { id = item.CategoryId, someCondition = true })


                    </div>

                }
            }


        }
        <!-- Category -->
        <!-- End-Category -->
       

       

        <div class="row">


            <div class="quantity">
                <div class="qtyContainer">
                    <span class="qtySpan" >Check Your Cart </span>
                
                </div>
                <span class="addItem"><a class="icon-shopping-cart" asp-action="ShadyCart" asp-controller="Menus" style="color:wheat"> check cart </a></span>
            </div>

        </div>

        



    </div>



</body>
</html>