Models/ShadyMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QRMenu.Models
{
    public class ShadyMenu
    {
        public int ShadyMenuId { get; set; }
        public string ItemNameAR { get; set; }
        public string ItemNameEN { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        //public string LogoImageURL { get; set; }
        public string Details { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

Areas/Administrator/Controllers/ShadyMenusController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QRMenu.Models;

namespace QRMenu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize(Roles = "Shady")]
    public class ShadyMenusController : Controller
    {
        private readonly AppDBContext _context;

        public ShadyMenusController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Administrator/ShadyMenus
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.shadyMenus.Include(s => s.Category);
            return View(await appDBContext.ToListAsync());
        }

        // GET: Administrator/ShadyMenus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shadyMenu = await _context.shadyMenus
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.ShadyMenuId == id);
            if (shadyMenu == null)
            {
                return NotFound();
            }

            return View(shadyMenu);
        }

        // GET: Administrator/ShadyMenus/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "NameAR");
            var model = new ShadyMenu();
            return View(model);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShadyMenuId,ItemNameAR,ItemNameEN,Price,ImageUrl,Details,CategoryId")] ShadyMenu menu, IFormFile ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null && ImageUrl.Length > 0)
                {
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageUrl.FileName;

                    // Determine the path where you want to save the image
                    var imagePath = Path.Combine("wwwroot/ItemImages", uniqueFileName);

                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await ImageUrl.CopyToAsync(stream);
                    }
                    menu.ImageUrl = "../ItemImages/" + uniqueFileName;
                }

                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", menu.CategoryId);
            return View(menu);
        }

        // GET: Administrator/ShadyMenus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shadyMenu = await _context.shadyMenus.FindAsync(id);
            if (shadyMenu == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", shadyMenu.CategoryId);
            return View(shadyMenu);
        }

        // POST: Administrator/ShadyMenus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShadyMenuId,ItemNameAR,ItemNameEN,Price,ImageUrl,Details,CategoryId")] ShadyMenu shadyMenu)
        {
            if (id != shadyMenu.ShadyMenuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shadyMenu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShadyMenuExists(shadyMenu.ShadyMenuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", shadyMenu.CategoryId);
            return View(shadyMenu);
        }

        // GET: Administrator/ShadyMenus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shadyMenu = await _context.shadyMenus
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.ShadyMenuId == id);
            if (shadyMenu == null)
            {
                return NotFound();
            }

            return View(shadyMenu);
        }

        // POST: Administrator/ShadyMenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shadyMenu = await _context.shadyMenus.FindAsync(id);
            _context.shadyMenus.Remove(shadyMenu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShadyMenuExists(int id)
        {
            return _context.shadyMenus.Any(e => e.ShadyMenuId == id);
        }
    }
}

Areas/Administrator/Views/ShadyMenus/Create.cshtml
@model QRMenu.Models.ShadyMenu

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>ShadyMenu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "ShadyMenus", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ItemNameAR" class="control-label"> الاسم باللغة العربية </label>
                    <input asp-for="ItemNameAR" class="form-control" />
                    <span asp-validation-for="ItemNameAR" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ItemNameEN" class="control-label"> Name In English</label>
                    <input asp-for="ItemNameEN" class="form-control" />
                    <span asp-validation-for="ItemNameEN" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label">السعر</label>
                    <input asp-for="Price" class="form-control"  id="priceInput" /> 
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label">ارفاق صورة </label>
                    <input type="file" class="form-control-file" id="ImageUrl" name="ImageUrl">
                    @*<span asp-validation-for="ImageUrl" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <label asp-for="Details" class="control-label">التفاصيل</label>
                    <input asp-for="Details" class="form-control" />
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryId" class="control-label">التصنيف</label>
                    <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>

        }
    </div>

</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    // Attach an event listener to the input field
    document.getElementById("priceInput").addEventListener("input", function () {
        var input = this.value.trim();

        // Use a regular expression to check if the input is a valid number (integer or decimal)
        if (/^\d+(\.\d{1,2})?$/.test(input)) {
            // Input is valid
            this.setCustomValidity('');
        } else {
            // Input is not valid
            this.setCustomValidity('Please enter a valid number.');
        }
    });
</script>

Areas/Administrator/Views/ShadyMenus/Delete.cshtml
@model QRMenu.Models.ShadyMenu

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShadyMenu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemNameAR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemNameAR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemNameEN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemNameEN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ShadyMenuId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Administrator/Views/ShadyMenus/Details.cshtml
@model QRMenu.Models.ShadyMenu

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ShadyMenu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemNameAR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemNameAR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemNameEN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemNameEN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ShadyMenuId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Administrator/Views/ShadyMenus/Edit.cshtml
@model QRMenu.Models.ShadyMenu

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ShadyMenu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ShadyMenuId" />
            <div class="form-group">
                <label asp-for="ItemNameAR" class="control-label"></label>
                <input asp-for="ItemNameAR" class="form-control" />
                <span asp-validation-for="ItemNameAR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemNameEN" class="control-label"></label>
                <input asp-for="ItemNameEN" class="form-control" />
                <span asp-validation-for="ItemNameEN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" id="priceInput" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<script>
    // Attach an event listener to the input field
    document.getElementById("priceInput").addEventListener("input", function () {
        var input = this.value.trim();

        // Use a regular expression to check if the input is a valid number (integer or decimal)
        if (/^\d+(\.\d{1,2})?$/.test(input)) {
            // Input is valid
            this.setCustomValidity('');
        } else {
            // Input is not valid
            this.setCustomValidity('Please enter a valid number.');
        }
    });
</script>

Areas/Administrator/Views/ShadyMenus/Index.cshtml
@model IEnumerable<QRMenu.Models.ShadyMenu>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="table-responsive">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemNameAR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemNameEN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemNameAR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemNameEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ShadyMenuId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ShadyMenuId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ShadyMenuId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
    </div>